project: 
  type: website

website:
  title: "Jenny Asquith - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/lillyasquith/lillyasquith.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Jenny Asquith 2024©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jennyasquith/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Data Cleansing"
        file: cleansing.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Cleansing_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Cleansing_Projects/project5.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



