---
layout: cv
title: Jenny Asquith
---
Web Developer, Junior Data Analyst

<div id="webaddress">
| <a href="http://github.com/byui-math-dept/lydang_spring24">	Academic Projects Link 1</a>
</div>

<div id="webaddress">
| <a href="http://https://github.com/lillyasquith"> Academic Projects Link2</a>
</div>

---
## Currently

Student at BYU-Idaho

### Specialized in

`Web Development | Databases`

Laguages: Python · C# · HTML5 · CSS · JavaScript · SQL · MySQL · SQL Server Management Studio


## Education

`Bachelor of Science in Applied Technology - April 2025`

__Brigham Young University–Idaho__

Overall GPA: 3.91 / 4.00

•	Implemented data dictionary, database security, backup and recovery, and explored cloud server solutions using SQL Server Management Studio and Google Cloud Platform.

•	Designed and managed relational databases for CRUD interactions

•	Practiced writing queries to a database combining multiple tables to retrieve desired information.

•	Employed Quarto and Python to analyze data and generate visually enhanced reports

•	Applied Python, HTML/CSS, and JavaScript to build various programs and applications. 

•	Created and maintained web frontends according to current standards of validity and practice

## Experience

`Full-Time Volunteer Representative`

__The Church of Jesus Christ of Latter-day Saints__

•	Located in Kansai region, Japan for 18 months to coordinate with other volunteers, assist in teaching English classes and participate in religious volunteering activities

•	Mentored 3 new volunteers to enhance their skills for the service

•	Became proficient in communication, interpersonal, English and Japanese skills


## Additional Information

•	Hard Skills: SQL Server Management Studio, Database Administration, SQL, MySQL, Data Visualization, Data Analytics, Excel, Python, C#, HTML5, CSS, JavaScript

•	Soft skills: Detail oriented, Critical thinking, Teamwork & collaboration, Work ethic, Digital technology, Strong communication skills

•	Certifications: Web and Computer Programing Certificate (2023), Database (in progress)


